# Generated by Django 5.0.1 on 2026-01-31 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_piggybank_piggybanktransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover',
        ),
    ]
