# Generated by Django 5.0.1 on 2026-01-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_profile_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
